name: "Mera pehla pipeline"

on:
  push:
    branches:
      - main
      - feature/**   # multiple branches allowed
  # workflow_dispatch:  # agar manually run karna ho

jobs:
  first_job:           # job-id (spaces allowed nahi)
    name: My first job
    runs-on: Ayansh-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print message
        run: echo "Hello, yeh mera pehla job hai!"

  second_job:          # job-id (unique hona chahiye)
    name: My second job
    runs-on: Ayansh-runner
    steps:
      - name: Print message
        run: echo "Hello, yeh mera dusra job hai!"
